var data={
  userInfo:{
    userId:1,
    nickName:"ahui",
    avatar:"",
    isAdmin:true,
    isAdvancedMember:true,
    activityApplyId:[
      21,22
    ]
  },
  activityList:[
    {
      activityId:21,
      activityName:"",
      activityDate:"2018-04-01",
      activityTime:"18:00-20:00",
      activityWeek:"2",
      activityPlace:"雅戈尔",
      activityAdmin:1,
      activityApplyMemberCount:12,
      activityMemberCount:30,
      activityCost:25
    },{
      activityId:22,
      activityName:"",
      activityDate:"2018-04-01",
      activityTime:"18:00-20:00",
      activityWeek:"2",
      activityPlace:"雅戈尔",
      activityAdmin:1,
      activityApplyMemberCount:12,
      activityMemberCount:30,
      activityCost:25
    },{
      activityId:22,
      activityName:"",
      activityDate:"2018-04-01",
      activityTime:"18:00-20:00",
      activityWeek:"2",
      activityPlace:"雅戈尔",
      activityAdmin:3,
      activityApplyMemberCount:12,
      activityMemberCount:30,
      activityCost:25
    },{
      activityId:22,
      activityName:"",
      activityDate:"2018-04-01",
      activityTime:"18:00-20:00",
      activityWeek:"2",
      activityPlace:"雅戈尔",
      activityAdmin:2,
      activityApplyMemberCount:12,
      activityMemberCount:30,
      activityCost:25
    }
  ]
};
module.exports=data;