var data={
  userInfo:{
    userId:1,
    isAdmin:true,
    apply:[
      1
    ]
  },
  activityList:[
    {
      activityId:1,
      name:"",
      date:"2018-04-01",
      time:"18:00-20:00",
      week:"2",
      place:"雅戈尔",
      adminId:1,
      headApply:12,
      headLimit:30,
      cost:25
    },{
      activityId:2,
      name:"",
      date:"2018-06-01",
      time:"17:00-20:30",
      week:"4",
      place:"启航",
      adminId:2,
      headApply:18,
      headLimit:25,
      cost:100
    }
  ]
};
module.exports=data;