var data={
  activityList:[
    {
      activityId:22,
      activityName:"",
      activityDate:"2018-04-01",
      activityTime:"18:00-20:00",
      activityWeek:"2",
      activityPlace:"雅戈尔",
      activityAdmin:2,
      activityApplyMemberCount:12,
      activityMemberCount:30,
      activityCost:25
    },{
      activityId:23,
      activityName:"",
      activityDate:"2018-04-01",
      activityTime:"18:00-20:00",
      activityWeek:"2",
      activityPlace:"启航",
      activityAdmin:2,
      activityApplyMemberCount:12,
      activityMemberCount:30,
      activityCost:25
    }
  ]
};
module.exports=data;